### ISSUE TITLE
Descrição etapas do projeto, task list e outros detalhes.

### ISSUE THREAD

**Issue by gcavalcantes** [gcavalcantes/TradutorLMS#1]
## Introdução
O projeto será dividido em três partes: Pesquisa, desenvolvimento e revisão.
## Pesquisa
Para o desenvolvimento de um tradutor para a linguagem LMS, é preciso ter ciência dos aspectos da linguagem como ela é apresentada na matéria.

- [x] Revisar conteúdo LMS.

- [x] Revisar projeto anteriores que envolvem o LMS.

- [x]  Fazer anotações para referência.

## Desenvolvimento
Este etapa consiste no desenvolvimento de um software que atinja as demandas do projeto. A linguagem de programação escolhida para realizar esta tarefa é a mesma utilizada nos projetos do Módulo Gerenciador e Módulo Léxico. Também será necessário pesquisar a melhor forma de se criar uma interface para o programa (este será o último passo desta etapa).
A etapa consiste, na maior parte, em criar um analisador semântico, que vai pegar o resultado do trabalho da análise léxica e análise sintática, fazendo a análise semântica e geração de código intermediário para a máquina hipotética.

- [ ] Pesquisar sobre como integrar os dois projetos anteriores a esse projeto.

- [ ] Criar uma programa para a análise semântica.

- [ ] Criar um programa para a geração do código intermediário.

- [ ] Criar uma interface que consiga reunir todas as funcionalidades.

## Revisão
Esta etapa consistem em revisar todo o conteúdo, principalmente na faze do desenvolvimento, certificando-se de que todos os critérios para o trabalho são atingidos.

- [ ] Verificar a integração entre projetos.

- [ ] Verificar os resultados da análise semântica.

- [ ] Verificar se a interface atinge as características demandadas.
